# Generated by Django 5.2.8 on 2025-12-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceitem',
            name='item_type',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('file', 'Файл')], default='photo', max_length=10),
        ),
    ]
