# Generated by Django 5.2.8 on 2025-12-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_alter_evidenceitem_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Опционально – подпись/описание реплики', max_length=255)),
                ('audio', models.FileField(help_text='Голосовое сообщение (ogg/mp3/wav и т.п.)', upload_to='trash_audio/')),
                ('speaker', models.CharField(choices=[('A', 'Собеседник A'), ('B', 'Собеседник B')], default='A', max_length=1)),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок в диалоге')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
